### ISSUE TITLE
Is there a way to add a texture preview?

### ISSUE THREAD

**Issue by ArEnSc** [KarlRamstedt/Modular-Options-Menu#1]
In this list say I want to add texture preview like a little square could I do that with these components?

**Comment by KarlRamstedt** [comment]
What are you referring to by "list"? The UI menu with options?

**Comment by ArEnSc** [comment]
I want to try to add a texture graphic to the list
<img width="881" alt="Screen Shot 2021-01-16 at 1 40 43 PM" src="https://user-images.githubusercontent.com/6252325/104820069-77516780-5800-11eb-8550-343a544fee0a.png">

**Comment by ArEnSc** [comment]
Sorry I realized how unclear any of that is, Can we add a square texture to an item in the options component ? 

<img width="881" alt="Screen Shot 2021-01-16 at 1 40 43 PM" src="https://user-images.githubusercontent.com/6252325/104820089-99e38080-5800-11eb-9b5f-01b4c5b01718.png">

**Comment by KarlRamstedt** [comment]
If you inherit from the base classes you can add whatever properties you want to the script.
If it's not a default property you can probably make a custom inspector for it. Just search around a bit and I'm sure you'll find what you need.
